server:
  port: 5000

management:
  #  endpoint:
  #    gateway:
  #      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" #gateway

spring:
  application:
    name: sample-api-gateway

  cloud:
    gateway:
      #동적 라우팅 설정
      routes:
        - id: reporting-service
          uri: http://localhost:8081
          predicates:
            - Path=/rtm/**
        #          filters:
        #            - AuthFilter

        - id: naver
          uri: http://naver.com
          predicates:
            - Path=/naver
      #          filters:
      #            - AuthFilter

  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create

  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    driverClassName: org.postgresql.Driver

  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      springframework:
        security: DEBUG