server:
  port: 5000

#jwt.secret: yiw1z2XJKQ7VHI
jwt:
#  key-set-uri: http://localhost:5000/.well-known/jwks.json
#  key: http://localhost:5000/.well-known/jwks.json
#  audience: jwt-audience
#  issuer: https://127.0.0.1:8081
#
  key: MjWP5L7CiD
#
#  subject: Authentication
#  issuer: "127.0.0.1:5000"
#  audience: "myApp"
#  secret: lcP5traclaaljt8ZaSf8
  issuer: "demo"
  audience: "web"
  subject: "demo"


spring:
  application:
    name: sample-api-gateway

  cloud:
    gateway:
      #동적 라우팅 설정
      routes:
        - id: reporting-service
          uri: http://localhost:8081
          predicates:
            - Path=/rtm/**
          filters:
            - JWTFilter=RSA256,HS256
            - RemoveResponseHeader=X-Powered-By

        - id: naver
          uri: http://naver.com
          predicates:
            - Path=/naver
          filters:
            - JWTFilter=RSA256,HS256
            - RemoveResponseHeader=X-Powered-By

  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create

  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    driverClassName: org.postgresql.Driver

  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      springframework:
        security: DEBUG