server:
  port:
    8081

eureka:
  client:
    register-with-eureka: true # false : unuse
    fetch-registry: true #false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:

  application:
    name: api-service


  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none

  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    driverClassName: org.postgresql.Driver

  security:
    user:
      name: gm
      password: 1234
      roles: USER
#    disable: true # temporary

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    example.pgConfig: info
