
server:
  port: 8761 #${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    #for remove error messgae
    renewalPercentThreshold: 0.85